import Link from 'next/link'
import Image from 'next/image'
import cart from '../images/cart.png'
import Head from 'next/head'

const Navbar = () => {
  return (
    <>
      <Head>
        <title>Swop Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="nav-outside container">
        <div className="nav-top">
          <label>Free Shipping For Orders Over $80 </label>
          <div className="nav-top-item">
            <ul>
              <li>
                <Link href="/help">Help Center</Link>
              </li>
              <li>
                <Link href="/return-policy">Returns</Link>
              </li>
              <li>
                <Link href="/contact">Contact</Link>
              </li>
              <li>
                <Link href="/witepaper">Whitepaper</Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="nav-bottom">
          <h2>
            <Link href="/">SWOP</Link>
          </h2>
          <div className="nav-bottom-item">
            <ul>
              <li>
                <Link href="/shop">Shop</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li>
                <Link href="/dapp">DApp Explorer</Link>
              </li>
              <li>
                <Link href="/qr-generator">QR Generator</Link>
              </li>
            </ul>
          </div>
          <h3>
            Cart{' '}
            <Image src={cart} alt="cart-icon" height="17" id="cart-image" />
          </h3>
        </div>
      </div>
    </>
  )
}

export default Navbar
